# Generated by Django 2.2.2 on 2019-07-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowordcloud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeurl',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
